No exit when union_helper not found (#99)
* Add test that checks that try doesnt exit if unionfs and mergerfs are not found

* Try now doesn't exit if unionfs/mergerfs are not found

* symlink instead of copying in the no-mergerfs test

* Remove /bin from test because things are not properly deleted

* deduplicate top dirs and mounts

* send try output to a file so that the test has minimal requirements

* Run no-union/mergerfs test in tempdir Sometimes it will fail when the home dir is a nested mount

---------

Co-authored-by: Eric Zhu <eric@debian-BULLSEYE-live-builder-AMD64>

diff --git a/try b/try
--- a/try
+++ b/try
@@ -49,6 +49,12 @@ try() {
     export SANDBOX_DIR
     mkdir -p "$SANDBOX_DIR/upperdir" "$SANDBOX_DIR/workdir" "$SANDBOX_DIR/temproot"
 
+    ## Find all the directories and mounts that need to be mounted
+    export DIRS_AND_MOUNTS=$(mktemp)
+    ls / | sed -e 's/^/\//' >"$DIRS_AND_MOUNTS"
+    findmnt --real -r -o target -n >>"$DIRS_AND_MOUNTS"
+    sort -u -o "$DIRS_AND_MOUNTS" "$DIRS_AND_MOUNTS"
+
     # we will overlay-mount each root directory separately (instead of all at once) because some directories cannot be overlayed
     # so we set up the mount points now
     #
@@ -61,7 +67,7 @@ try() {
     # -r: raw output
     # -o target: only print the mount target
     # then we want to exclude the root partition "/"
-    for mountpoint in /* $(findmnt --real -r -o target -n | grep -v "^/$")
+    for mountpoint in $(cat "$DIRS_AND_MOUNTS")
     do
         ## Only make the directory if the original is a directory too
         if [ -d "$mountpoint" ]
@@ -118,8 +124,15 @@ autodetect_union_helper() {
     fi
 }
 
+# Detect if union_helper is set, if not, we try to autodetect them
+if [ -z "$union_helper" ]
+then
+    ## Try to detect the union_helper (the variable could still be empty afterwards).
+    union_helper="$(autodetect_union_helper)"
+fi
+
 # actually mount the overlays
-for mountpoint in /* $(findmnt --real -r -o target -n)
+for mountpoint in $(cat "$DIRS_AND_MOUNTS")
 do
     ## We are not interested in mounts that are not directories
     if [ ! -d "$mountpoint" ]
@@ -140,18 +153,6 @@ do
     # If mounting everything normally fails, we try using either using mergerfs or unionfs to mount them.
     if [ "$?" -ne 0 ]
     then
-        # Detect if union_helper is set, if not, we try to autodetect them
-        if [ -z ${union_helper+x} ]
-        then
-            union_helper="$(autodetect_union_helper)"
-            if [ -z "$union_helper" ]
-            then
-                printf "%s: Failed to mount overlayfs normally, mergerfs or unionfs not found for $mountpoint, see $try_mount_log\n" "$TRY_COMMAND" >&2
-                exit 1
-            fi
-        fi
-
-
         ## If the overlay failed, it means that there is a nested mount inside the target mount, e.g., both `/home` and `/home/user/mnt` are mounts.
         ## To address this, we use unionfs/mergerfs (they support the same functionality) to show all mounts under the target mount as normal directories.
         ## Then we can normally make the overlay on the new union directory.
@@ -162,15 +163,22 @@ do
         ##               We should try to investigate either:
         ##               1. Not doing another overlay if we have done it for a parent directory (we can keep around a list of overlays and skip if we are in a child)
         ##               2. Do one unionfs+overlay at the root `/` once and be done with it!
-        merger_dir=$(mktemp -d)
 
-        ## Create a union directory
-        "$union_helper" $mountpoint $merger_dir 2>> "$try_mount_log" || 
-            printf "%s: Warning: Failed to mount $mountpoint via $union_helper, see \"$try_mount_log\"\n" "$TRY_COMMAND" >&2
-        
-        ## Make the overlay on the union directory which works as a lowerdir for overlay
-        make_overlay "$SANDBOX_DIR" "$merger_dir" "$mountpoint" 2>> "$try_mount_log" ||
-        printf "%s: Warning: Failed mounting $mountpoint as an overlay via $union_helper, see \"$try_mount_log\"\n" "$TRY_COMMAND" >&2
+        if [ -z "$union_helper" ]
+        then
+            ## We can ignore this mountpoint, if the user program tries to use it, it will crash, but if not we can run normally
+            printf "%s: Warning: Failed mounting $mountpoint as an overlay and mergerfs or unionfs not set and could not be found, see \"$try_mount_log\"\n" "$TRY_COMMAND" >&2
+        else
+            merger_dir=$(mktemp -d)
+
+            ## Create a union directory
+            "$union_helper" $mountpoint $merger_dir 2>> "$try_mount_log" ||
+                printf "%s: Warning: Failed mounting $mountpoint via $union_helper, see \"$try_mount_log\"\n" "$TRY_COMMAND" >&2
+
+            ## Make the overlay on the union directory which works as a lowerdir for overlay
+            make_overlay "$SANDBOX_DIR" "$merger_dir" "$mountpoint" 2>> "$try_mount_log" ||
+            printf "%s: Warning: Failed mounting $mountpoint as an overlay via $union_helper, see \"$try_mount_log\"\n" "$TRY_COMMAND" >&2
+        fi
     fi
 done
 
