first cut at a style guide

diff --git a/try b/try
--- a/try
+++ b/try
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (c) 2023 The PaSh Authors. 
+# Copyright (c) 2023 The PaSh Authors.
 #
 # Usage of this source code is governed by the MIT license, you can find the
 # LICENSE file in the root directory of this project.
@@ -18,7 +18,7 @@ export TRY_COMMAND
 # 2 -- input error
 
 ################################################################################
-# Run a command in an overlay
+# Run a command (in `$@`) in an overlay (in `$SANDBOX_DIR`)
 ################################################################################
 
 try() {
@@ -146,7 +146,7 @@ do
         [ "$mountpoint" = "/dev" ] || [ "$mountpoint" = "/proc" ]
     then
         continue
-    fi    
+    fi
 
     # Try mounting everything normally
     make_overlay "$SANDBOX_DIR" "/$mountpoint" "$mountpoint" 2>> "$try_mount_log"
@@ -204,8 +204,8 @@ EOF
     cat >"$chroot_executable" <<EOF
 #!/bin/sh
 
-mount -t proc proc /proc &&   
-cd $START_DIR && 
+mount -t proc proc /proc &&
+cd $START_DIR &&
 . "$script_to_execute"
 EOF
 
@@ -249,7 +249,7 @@ EOF
 }
 
 ################################################################################
-# Summarize an overlay
+# Summarize the ovelray in `$SANDBOX_DIR`
 ################################################################################
 
 summary() {
@@ -260,11 +260,11 @@ summary() {
     then
         error "could not find directory $SANDBOX_DIR/upperdir" 1
     fi
-    
+
     ## Finds all potential changes
     changed_files=$(find_upperdir_changes "$SANDBOX_DIR" "$IGNORE_FILE")
     summary_output=$(process_changes "$SANDBOX_DIR" "$changed_files")
-    
+
     if [ -z "$summary_output" ]
     then
         return 1
@@ -291,7 +291,7 @@ EOF
 }
 
 ################################################################################
-# Commit the results of an overlay
+# Commit the results of an overlay in `$SANDBOX_DIR`
 ################################################################################
 
 commit() {
@@ -316,58 +316,80 @@ commit() {
         (mo*) cp -fa "$changed_file" "$local_file";;
         (ad*) cp -fa "$changed_file" "$local_file"
         esac
-    
+
         if [ $? -ne 0 ]
         then
-	    warn "couldn't commit $changed_file"
+            warn "couldn't commit $changed_file"
         fi
     done <<EOF
 $summary_output
 EOF
 }
 
-## Checks if a file is an overlayfs whiteout file
+################################################################################
+# Checks if a file is an overlayfs whiteout file
+################################################################################
+
 is_whiteout_file() {
     file="$1"
+
     [ -c "$file" ] && ! [ -s "$file" ] && [ "$(stat -c %t,%T "$file")" = "0,0" ]
 }
 
+################################################################################
 ## Defines which changes we want to ignore in the summary and commit
+################################################################################
+
 ignore_changes() {
     ignore_file="$1"
+
     grep -v -f "$ignore_file"
 }
 
+################################################################################
 ## Lists all upperdir changes in raw format
+################################################################################
+
 find_upperdir_changes() {
     sandbox_dir="$1"
     ignore_file="$2"
+
     find "$sandbox_dir/upperdir/" -type f -o \( -type c -size 0 \) -o -type d | ignore_changes "$ignore_file"
 }
 
 
-## Processes upperdir changes to an internal format that can be processed by summary and commit
-## Format:
-## XX PATH
-## where:
-##  XX is a two character code for the modification
-##  - rd: Replaced with a directory
-##  - md: Created a directory
-##  - de: Deleted a file
-##  - mo: Modified a file
-##  - ad: Added a file
-##  PATH is the local path
+################################################################################
+# Processes upperdir changes to an internal format that can be processed by summary and commit
+#
+# Output format:
+#
+#   XX PATH
+#
+#   where:
+#     XX is a two character code for the modification
+#     - rd: Replaced with a directory
+#     - md: Created a directory
+#     - de: Deleted a file
+#     - mo: Modified a file
+#     - ad: Added a file
+#
+#     PATH is the local/host path (i.e., without the upper
+#
+################################################################################
+
 process_changes() {
     sandbox_dir="$1"
     changed_files="$2"
-    while IFS= read -r changed_file; do
+
+    while IFS= read -r changed_file
+    do
         local_file="${changed_file#$sandbox_dir/upperdir}"
         if [ -d "$changed_file" ] && ! [ -d "${local_file}" ]
         then # new directory
             ## If something exists there, we need to delete it first
             if [ -e "$local_file" ]
             then
-                echo "rd $local_file" 
+                echo "rd $local_file"
             else
                 echo "md $local_file"
             fi
@@ -388,22 +410,25 @@ $changed_files
 EOF
 }
 
-## Returns 0 if a sandbox is empty (fresh for use)
-## or if it already exists, and is well-formed 
+################################################################################
+# Returns 0 if a sandbox is empty (fresh for use) or pre-existing and well formed
+################################################################################
+
 sandbox_valid_or_empty() {
     sandbox_dir="$1"
+
     if [ ! -d "$sandbox_dir/upperdir" ] && [ ! -d "$sandbox_dir/workdir" ] && [ ! -d "$sandbox_dir/temproot" ]
     then
-        ## No sandbox directory exists so we can happily return
+        # No sandbox directory exists so we can happily return
         return 0
     fi
 
-    ## The sandbox already exists so we now need to check if it is valid
-    ## Validity requirements:
-    ## - no file exists in the temproot tree, i.e., all directories are empty
-    ##
-    ## TODO: Make this validity assertion tighter
-    ## KK 2023-06-28 workdir seems to be non-empty after a single use, is that expected?
+    # The sandbox already exists so we now need to check if it is valid
+    # Validity requirements:
+    # - no file exists in the temproot tree, i.e., all directories are empty
+    #
+    # TODO: Make this validity assertion tighter
+    # KK 2023-06-28 workdir seems to be non-empty after a single use, is that expected?
     if [ ! -z "$(find "$sandbox_dir/temproot" -depth -not -type d)" ]
     then
         return 1
@@ -413,16 +438,25 @@ sandbox_valid_or_empty() {
 }
 
 ################################################################################
-# Error messaging
+# Emit a warning
 ################################################################################
 
 warn() {
-    printf "%s: %s\n" "$TRY_COMMAND" "$1" >&2
+    msg="$1"
+
+    printf "%s: %s\n" "$TRY_COMMAND" "$msg" >&2
 }
 
+################################################################################
+# Emit a warning and exit
+################################################################################
+
 error() {
-    warn "$1"
-    exit "$2"
+    msg="$1"
+    exitcode="$2"
+
+    warn "$msg"
+    exit "$exitcode"
 }
 
 ################################################################################
@@ -438,7 +472,7 @@ Usage: $TRY_COMMAND [-nvhy] [-i PATTERN] [-D DIR] [-U PATH] CMD [ARG ...]
   -i PATTERN        ignore paths that match PATTERN on summary and commit
   -D DIR            work in DIR (implies -n)
   -U PATH           path to unionfs helper (e.g., mergerfs, unionfs-fuse)
-  
+
   -v                show version information (and exit)
   -h                show this usage message (and exit)
 
@@ -467,24 +501,26 @@ IGNORE_FILE=$(mktemp)
 while getopts ":yvni:D:U:" opt
 do
     case "$opt" in
-        (y) NO_COMMIT="commit";;
-        (n) NO_COMMIT="show";;
-        (i) echo $OPTARG >>"$IGNORE_FILE";;
-        (D) if ! [ -d "$OPTARG" ]
-            then
-                error "could not find sandbox directory '$OPTARG'" 2
-            fi
-            SANDBOX_DIR="$OPTARG"
-            NO_COMMIT="quiet"
-            ;;
-        (v) echo "$TRY_COMMAND version $TRY_VERSION" >&2; exit 0;;
-        (U) if ! [ -x "$OPTARG" ]
-            then
-                error "could not find executable union helper '$OPTARG'" 2
-            fi
-            union_helper="$OPTARG" 
-            ;;
-        (h|*) usage; exit 0;;
+        (y)   NO_COMMIT="commit";;
+        (n)   NO_COMMIT="show";;
+        (i)   echo $OPTARG >>"$IGNORE_FILE";;
+        (D)   if ! [ -d "$OPTARG" ]
+              then
+                  error "could not find sandbox directory '$OPTARG'" 2
+              fi
+              SANDBOX_DIR="$OPTARG"
+              NO_COMMIT="quiet"
+              ;;
+        (v)   echo "$TRY_COMMAND version $TRY_VERSION" >&2
+              exit 0;;
+        (U)   if ! [ -x "$OPTARG" ]
+              then
+                  error "could not find executable union helper '$OPTARG'" 2
+              fi
+              union_helper="$OPTARG"
+              ;;
+        (h|*) usage
+              exit 0;;
     esac
 done
 
@@ -497,11 +533,15 @@ then
 fi
 
 case "$1" in
-    (summary) : ${SANDBOX_DIR=$2}; summary;;
-    (commit) : ${SANDBOX_DIR=$2}; commit;;
-    (explore) : ${SANDBOX_DIR=$2}; try "$SHELL";;
-    (--) shift; try "$@";;
-    (*) try "$@";;
+    (summary) : ${SANDBOX_DIR=$2}
+              summary;;
+    (commit)  : ${SANDBOX_DIR=$2}
+              commit;;
+    (explore) : ${SANDBOX_DIR=$2}
+              try "$SHELL";;
+    (--)      shift
+              try "$@";;
+    (*)       try "$@";;
 esac
 
 exit $exitcode
