improve docs, refactor from top_dir to mountpoint

diff --git a/try b/try
--- a/try
+++ b/try
@@ -35,11 +35,11 @@ try() {
     # -r: raw output
     # -o target: only print the mount target
     # then we want to exclude the root partition "/"
-    for top_dir in /* $(findmnt --real -r -o target -n | grep -v "^/$")
+    for mointpoint in /* $(findmnt --real -r -o target -n | grep -v "^/$")
     do
         ## Only make the directory if the original is a directory too
-        if [ -d "$top_dir" ]; then
-            mkdir -p "$SANDBOX_DIR"/upperdir/"$top_dir" "$SANDBOX_DIR"/workdir"/$top_dir" "$SANDBOX_DIR"/temproot/"$top_dir"
+        if [ -d "$mointpoint" ]; then
+            mkdir -p "$SANDBOX_DIR"/upperdir/"$mointpoint" "$SANDBOX_DIR"/workdir"/$mointpoint" "$SANDBOX_DIR"/temproot/"$mointpoint"
         fi
     done
 
@@ -50,20 +50,21 @@ try() {
 #!/bin/sh
 
 # actually mount the overlays
-for top_dir in /* $(findmnt --real -r -o target -n | grep -v "^/$")
+for mointpoint in /* $(findmnt --real -r -o target -n | grep -v "^/$")
 do
     ## If the directory is not a mountpoint
-    if [ -d "$top_dir" ]; then 
-        # skip if it is /dev or /proc
-        if [ "$top_dir" = "/dev" ] || [ "$top_dir" = "/proc" ]; then
+    if [ -d "$mointpoint" ]; then 
+        # skip if it is /dev or /proc, we will mount it later
+        if [ "$mointpoint" = "/dev" ] || [ "$mointpoint" = "/proc" ]; then
             continue
         fi
-        mount -t overlay overlay -o lowerdir=/"$top_dir",upperdir="$SANDBOX_DIR"/upperdir/"$top_dir",workdir="$SANDBOX_DIR"/workdir/"$top_dir" "$SANDBOX_DIR"/temproot/"$top_dir" 2>> "$try_mount_log"
+        mount -t overlay overlay -o lowerdir=/"$mointpoint",upperdir="$SANDBOX_DIR"/upperdir/"$mointpoint",workdir="$SANDBOX_DIR"/workdir/"$mointpoint" "$SANDBOX_DIR"/temproot/"$mointpoint" 2>> "$try_mount_log"
         if [ $? -ne 0 ]; then
+            # Here we use mergerfs/unionfs to be mounted into a single file system. Used to fix nested mounts #19
             merger_dir=$(mktemp -d)
-            mergerfs $top_dir $merger_dir 2>> "$try_mount_log" || echo "Warning: Failed to mount $top_dir via mergerfs" 1>&2 &&
-            mount -t overlay overlay -o lowerdir="$merger_dir",upperdir="$SANDBOX_DIR"/upperdir"$top_dir",workdir="$SANDBOX_DIR"/workdir"$top_dir" "$SANDBOX_DIR"/temproot"$top_dir" 2>> "$try_mount_log" ||
-            echo "Warning: Failed mounting $top_dir as an overlay via mergerfs, see "$try_mount_log"" 1>&2
+            mergerfs $mointpoint $merger_dir 2>> "$try_mount_log" || echo "Warning: Failed to mount $mointpoint via mergerfs" 1>&2 &&
+            mount -t overlay overlay -o lowerdir="$merger_dir",upperdir="$SANDBOX_DIR"/upperdir"$mointpoint",workdir="$SANDBOX_DIR"/workdir"$mointpoint" "$SANDBOX_DIR"/temproot"$mointpoint" 2>> "$try_mount_log" ||
+            echo "Warning: Failed mounting $mointpoint as an overlay via mergerfs, see "$try_mount_log"" 1>&2
         fi
     fi
 done
